after_success:
  - npm install codeclimate-test-reporter && cat coverage/lcov.info | codeclimate-test-reporter
cache:
  directories:
    - node_modules
language: node_js
node_js:
  - "6"
script:
  - npm test
sudo: required
install:
  - npm install
