jobs:
  build:
    working_directory: ~/code-gov
    docker:
      - image: circleci/node:6.11.0
    steps:
      - checkout
      - run:
          name: Add Node Module's bin to PATH
          command: echo "export PATH=`pwd`/node_modules/.bin:$PATH" >> $BASH_ENV
      - restore_cache:
          key: code-gov-web-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: code-gov-web-{{ checksum "package.json" }}
          paths:
            - code-gov-web/node_modules
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Install CodeClimate Test Reporter
          command: npm install codeclimate-test-reporter
      - run:
          name: Run CodeClimate Test Reporter
          command: codeclimate-test-reporter < coverage/lcov.info
